---
title: "Practice 3.2"
author: "Shu-Li Dubbink"
date: "2022-10-05"
output: html_document
---

# Practice 3.2

##Step 1 
Clearing the environment and creating the dataframe from the table in R, calling it Bubble

```{r}
rm(list=ls())
Person <- c("subject_1", "subject_2", "subject_3", "subject_4", "subject_5")
Before_diet <- c(104, 95, 87, 77, 112)
After_diet <-c(96, 91, 81, 75, 118)
Bubble  <- data.frame(Person, Before_diet, After_diet)
```

##Step 2 
Creating the components of WEIGHT_LOSS and then creating the list WEIGHT_LOSS

```{r}
Weightloss_percentage <- c((Bubble$Before_diet-Bubble$After_diet)/Bubble$Before_diet*100)
Subject <- Person
Weight_loss_table <- data.frame (Subject,Weightloss_percentage)
WEIGHT_LOSS <- list(A=Subject, B=Weightloss_percentage, C=Weight_loss_table)
```

##Step 3 
Add message

```{r}
message<- c("I do not really like nor dislike data manipulation")
```

## Step 4
Make the list BUBBLE_DIET

```{r}
BUBBLE_DIET <- list(A=Bubble, B=WEIGHT_LOSS, C=message)
```

